apiVersion: v2
name: shareit
description: A Helm chart for ShareIt application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: chart-gateway
    version: 0.1.0
    repository: file://../chart-gateway

  - name: chart-server
    version: 0.1.0
    repository: file://../chart-server

  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.17

  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.10.2

  - name: prometheus
    version: 25.24.1
    repository: https://prometheus-community.github.io/helm-charts

  - name: jaeger
    version: 3.1.1
    repository: https://jaegertracing.github.io/helm-charts