chart-gateway:
  server:
    host: server

chart-server:
  datasource:
    host: postgres


postgresql:
  fullnameOverride: postgres
  auth:
    username: evgenii
    password: postgres
    database: share