chart-gateway:
  server:
    host: server

chart-server:
  datasource:
    host: postgres


postgresql:
  fullnameOverride: postgres
  auth:
    username: evgenii
    password: postgres
    database: share

jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

gatewayingress:
  controller:
    ingressClassResource:
      controllerValue: k8s.io/gatewayingress
      name: gatewayingress
    service:
      ports:
        http: 8090

jaegeringress:
  controller:
    ingressClassResource:
      controllerValue: k8s.io/jaegeringress
      name: jaegeringress
    service:
      ports:
        http: 16686