services:
  gateway:
    build: gateway
    image: gateway:1.0.0
    container_name: ShareItGateway
    ports:
      - "8090:8090"
    depends_on:
      - server
      - jaeger
    environment:
      - SHAREIT_SERVER_URL=http://server:9091
      - OTEL_SERVICE_NAME=Gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318

  server:
    build: server
    image: server:1.0.0
    container_name: ShareItServer
    ports:
      - "9091:9091"
    depends_on:
      - db
      - jaeger
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OTEL_SERVICE_NAME=Server
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318

  db:
    image: postgres:14
    container_name: ShareItDB
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./server/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
      - gateway

  flyway:
    build: migration
    container_name: migration
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/share
      - FLYWAY_USER=postgres
      - ENV FLYWAY_PASSWORD=postgres

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"