services:
  gateway:
    build: gateway
    image: gateway:1.0.0
    container_name: ShareItGateway
    ports:
      - "8090:8090"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9091

  server:
    build: server
    image: server:1.0.0
    container_name: ShareItServer
    ports:
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share
      - POSTGRES_USER=evgenii
      - POSTGRES_PASSWORD=12345678

  db:
    image: postgres:16.3
    container_name: ShareItDB
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=evgenii
      - POSTGRES_PASSWORD=12345678