services:
  gateway:
    build: gateway
    image: gateway:1.0.0
    container_name: ShareItGateway
    ports:
      - "8090:8090"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9091

  server:
    build: server
    image: server:1.0.0
    container_name: ShareItServer
    ports:
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:14
    container_name: ShareItDB
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./server/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
      - gateway

  flyway:
    build: migration
    container_name: migration
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/share
      - FLYWAY_USER=postgres
      - ENV FLYWAY_PASSWORD=postgres