global:
  scrape_interval: 15s  # Задайте интервал опроса

scrape_configs:
  - job_name: 'shareit-monitoring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['server:9091']