apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: 'true'  # Указывает Prometheus собирать метрики с этого сервиса
    prometheus.io/scheme: 'http'  # Указывает использовать HTTP схему для подключения
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/scrape_interval: "15s"
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          env:
            - name: SERVER_PORT
              value: "9091"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/share"
            - name: POSTGRES_USER
              value: {{ .Values.datasource.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.datasource.postgresPassword }}