apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    "helm.sh/resource-policy": keep
    timestamp: "{{ .Values.migration.timestamp }}"
spec:
  template:
    metadata:
      labels:
        app: migration
      annotations:
        timestamp: "{{ .Values.migration.timestamp }}"
    spec:
      containers:
        - name: {{ .Values.migration.containerName}}
          image: {{ .Values.migration.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres:{{ .Values.db.port }}/{{ .Values.db.postgresDb }}"
            - name: FLYWAY_USER
              value: "{{ .Values.db.postgresUser }}"
            - name: FLYWAY_PASSWORD
              value: "{{ .Values.db.postgresPassword }}"
          args:
            - -url=$(FLYWAY_URL)
            - -user=$(FLYWAY_USER)
            - -password=$(FLYWAY_PASSWORD)
            - migrate
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 3