apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    "helm.sh/resource-policy": keep
    timestamp: "{{ .Values.migration.timestamp }}"
spec:
  template:
    metadata:
      labels:
        app: migration
      annotations:
        timestamp: "{{ .Values.migration.timestamp }}"
    spec:
      containers:
        - name: {{ .Values.migration.containerName}}
          image: {{ .Values.migration.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres:{{ .Values.db.port }}/{{ .Values.db.postgresDb }}"
            - name: FLYWAY_USER
              value: "{{ .Values.db.postgresUser }}"
            - name: FLYWAY_PASSWORD
              value: "{{ .Values.db.postgresPassword }}"
            - name: PROMETHEUS_PUSHGATEWAY
              value: {{ .Values.migration.prometheusPushgateway }}
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "migration-script.sh" ]
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 3