apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: {{ .Values.db.containerName }}
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.db.postgresDb }}"
            - name: POSTGRES_USER
              value: "{{ .Values.db.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.db.postgresPassword }}"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc