apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
  selector:
    app: gateway