apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: {{ .Values.gateway.containerName }}
          image: {{ .Values.gateway.image }}
          ports:
            - containerPort: {{ .Values.gateway.port }}
          env:
            - name: SHAREIT_SERVER_URL
              value: "http://server-service:9090"