apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 30080
      targetPort: {{ .Values.gateway.port }}
  selector:
    app: gateway