apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-db-service:5432/shareit"
            - name: POSTGRES_USER
              value: "{{ .Values.server.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.server.postgresPassword }}"