apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  selector:
    app: server