image: "server:1.0.0"
port: 9091
targetPort: 9091
name: server
datasource:
  host: host
  postgresUser: evgenii
  postgresPassword: postgres
probes:
  livenessProbe:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 2