image: "gateway:1.0.0"
port: 8090
targetPort: 8090
name: gateway
server:
  host: host
  port: 9091

probes:
  livenessProbe:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 1
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 2