image: "gateway:1.0.0"
port: 8090
targetPort: 8090
name: gateway
server:
  host: host
  port: 9091

probes:
  livenessProbe:
    path: /actuator/health/liveness
    initialDelaySeconds: 90
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
    initialDelaySeconds: 90
    periodSeconds: 15